name: "IoT Certbot"
description: "Configure certbot using an AWS IoT device identity + Route 53 DNS"
url: https://github.com/offbyone/homeassistant-addons/iot-certbot
version: "1.0.10"
slug: iot_certbot
init: false
startup: services
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386

map:
  - ssl:rw
  - config

options:
  domains:
    - null
  email: null
  keyfile: privkey.pem
  certfile: fullchain.pem
  interval: 3600
  iot:
    thing_name: null
    role_alias: null
    endpoint_url: null

schema:
  domains:
    - str
  email: email
  keyfile: str
  certfile: str
  interval: int?
  acme_root_ca_cert: str?
  acme_server: url?
  iot:
    thing_name: str
    role_alias: str
    endpoint_url: str
